# custom_cursor_colors = true

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 14

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Normal"

[font.offset]
x = 0
y = 0

[window]
dynamic_padding = true
opacity = 1.0

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 4
y = 4

[colors]
draw_bold_text_with_bright_colors = false

# [general]
# import = ["/home/zac/.config/alacritty/alacritty/dist/rose-pine-moon.yml"]
    # "~/.config/alacritty/themes/themes/gnome_terminal.toml"
[general]
import = [
    "~/.config/alacritty/themes/themes/rose_pine.toml"
]
