# 
format = """
[ ](fg:#286983)\ 
[  ](bg:#286983 fg:#fffaf3)\
[](fg:#286983)\
$directory\
[](fg:#ea9d34)\
$git_branch\
$git_status\
[](fg:#907aa9)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#d7827e)\
$time\
[](fg:#56949f)\
 $character"""

[directory]
style = "fg:#ea9d34"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
# style = "bg:#907aa9"
format = '[[ $symbol $branch ](fg:#907aa9)]($style)'

[git_status]
# style = "bg:#907aa9"
format = '[[($all_status$ahead_behind )](fg:#907aa9)]($style)'

[nodejs]
symbol = ""
# style = "bg:#d7827e"
format = '[[ $symbol ($version) ](fg:#d7827e)]($style)'

[rust]
symbol = ""
# style = "bg:#d7827e"
format = '[[ $symbol ($version) ](fg:#d7827e)]($style)'

[golang]
symbol = "ﳑ"
# style = "bg:#d7827e"
format = '[[ $symbol ($version) ](fg:#d7827e)]($style)'

[php]
symbol = ""
# style = "bg:#d7827e"
format = '[[ $symbol ($version) ](fg:#d7827e)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# style = "bg:#403d52"
format = '[[  $time ](fg:#56949)]($style)'
