# 
format = """
[](fg:#403d52)\ 
[   ](bg:#403d52)\
[](fg:#403d52)\
$directory\
[](fg:#f6c177)\
$git_branch\
$git_status\
[](fg:#c4a7e7)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#ebbcba)\
$time\
[](fg:#9ccfd8)\
 $character"""

[directory]
style = "fg:#f6c177"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
# style = "bg:#c4a7e7"
format = '[[ $symbol $branch ](fg:#c4a7e7)]($style)'

[git_status]
# style = "bg:#c4a7e7"
format = '[[($all_status$ahead_behind )](fg:#c4a7e7)]($style)'

[nodejs]
symbol = ""
# style = "bg:#ebbcba"
format = '[[ $symbol ($version) ](fg:#ebbcba)]($style)'

[rust]
symbol = ""
# style = "bg:#ebbcba"
format = '[[ $symbol ($version) ](fg:#ebbcba)]($style)'

[golang]
symbol = "ﳑ"
# style = "bg:#ebbcba"
format = '[[ $symbol ($version) ](fg:#ebbcba)]($style)'

[php]
symbol = ""
# style = "bg:#ebbcba"
format = '[[ $symbol ($version) ](fg:#ebbcba)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# style = "bg:#403d52"
format = '[[  $time ](fg:#9ccfd8)]($style)'
