# 

format = """
[ ](fg:bright-black)\ 
[  ](bg:bright-black fg:bright-white)\
[](fg:bright-black)\
$directory\
[](fg:yellow)\
$git_branch\
$git_status\
[](fg:cyan)\
$nodejs\
$rust\
$golang\
$php\
[](fg:red)\
$time\
[](fg:blue)\
 $character"""

[directory]
style = "fg:bright-purple"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
# style = "bg:cyan"
format = '[[ $symbol $branch ](fg:cyan)]($style)'

[git_status]
# style = "bg:cyan"
format = '[[($all_status$ahead_behind )](fg:cyan)]($style)'

[nodejs]
symbol = ""
# style = "bg:red"
format = '[[ $symbol ($version) ](fg:red)]($style)'

[rust]
symbol = ""
# style = "bg:red"
format = '[[ $symbol ($version) ](fg:red)]($style)'

[golang]
symbol = "ﳑ"
# style = "bg:red"
format = '[[ $symbol ($version) ](fg:red)]($style)'

[php]
symbol = ""
# style = "bg:red"
format = '[[ $symbol ($version) ](fg:red)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
# style = "bg:bright-black"
format = '[[  $time ](fg:#56949)]($style)'
