#! /bin/sh

xsetroot -cursor_name left_ptr
picom &
nitrogen --restore
nm-applet &
blueman-applet &
conky &
asusctltray &
env fish_tmux_autoconnect=false alacritty --class scratchterm&
bspc rule -a scratchterm sticky=on state=floating hidden=on
/bin/sh /home/zac/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc config focused_border_color "#88C0D0"
# bspc config normal_border_color "#3B4252"
# bspc config presel_feedback_color "#4C566A"
bspc config focused_border_color "#f6c177"
bspc config normal_border_color "#403d52"
bspc config presel_feedback_color "#6e6a86"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a Zathura state=tiled
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
