wallpaper {
    monitor = eDP-1
    path = /usr/share/backgrounds/default-dark.jxl
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /usr/share/backgrounds/default-dark.jxl
    fit_mode = cover
}
